production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:  # Explicitly define the cable database
    <<: *default
    url: <%= ENV["CABLE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate